version: '3.8'

services:
  portainer:
    image: portainer/portainer
    privileged: true
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped
    networks:
      - nginx

networks:
  default:
    external: true
    name: nginx
