version: '3.8'

services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer
    privileged: true
    volumes:
      - './portainer_data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped
    ports:
      - '8000:8000'
      - '9443:9443'

networks:
  default:
    external: true
    name: nginx
